
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
(function () {
  var existing = window.APP_CONFIG || {};
  var override = window.LIKESTUDIO_API_BASE_URL;
  var defaultBase = "https://apis.listoapp.es/like_api";


  var baseUrl = (override || existing.API_BASE_URL || defaultBase).replace(/\/+$/, "");

  
  window.APP_CONFIG = {
  
    API_BASE_URL: baseUrl
  };


})();

//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
//DONT FORGET TO CHAN GE THE BASE URL FOR LOCAL DEVELOPMENT
